# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transaction_pattern_api import TransactionPatternApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionPatternApi(unittest.TestCase):
    """TransactionPatternApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transaction_pattern_api.TransactionPatternApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_activate_transaction_pattern(self):
        """Test case for activate_transaction_pattern

        Enable a transaction pattern  # noqa: E501
        """
        pass

    def test_delete_transaction_pattern(self):
        """Test case for delete_transaction_pattern

        Delete transaction pattern  # noqa: E501
        """
        pass

    def test_get_transaction_pattern(self):
        """Test case for get_transaction_pattern

        Get transaction pattern  # noqa: E501
        """
        pass

    def test_list_transaction_patterns(self):
        """Test case for list_transaction_patterns

        List transaction patterns for account  # noqa: E501
        """
        pass

    def test_post_transaction_pattern(self):
        """Test case for post_transaction_pattern

        Create a new pattern  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
