# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.transaction_summary_api import TransactionSummaryApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTransactionSummaryApi(unittest.TestCase):
    """TransactionSummaryApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.transaction_summary_api.TransactionSummaryApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_summary(self):
        """Test case for list_summary

        List account summaries  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
