# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notification_target_api import NotificationTargetApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationTargetApi(unittest.TestCase):
    """NotificationTargetApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.notification_target_api.NotificationTargetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_notification_target(self):
        """Test case for delete_notification_target

        Delete notification target  # noqa: E501
        """
        pass

    def test_get_notification_target(self):
        """Test case for get_notification_target

        Get notification target  # noqa: E501
        """
        pass

    def test_get_notification_targets(self):
        """Test case for get_notification_targets

        List notification targets  # noqa: E501
        """
        pass

    def test_post_notification_target(self):
        """Test case for post_notification_target

        Create a new notification target  # noqa: E501
        """
        pass

    def test_put_notification_target(self):
        """Test case for put_notification_target

        Update notification target  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
