# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.account_api import AccountApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountApi(unittest.TestCase):
    """AccountApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.account_api.AccountApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_account(self):
        """Test case for delete_account

        Delete account  # noqa: E501
        """
        pass

    def test_get_account(self):
        """Test case for get_account

        Get account  # noqa: E501
        """
        pass

    def test_get_accounts(self):
        """Test case for get_accounts

        List accounts  # noqa: E501
        """
        pass

    def test_update_account(self):
        """Test case for update_account

        Update account name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
