# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.forecast_api import ForecastApi  # noqa: E501
from swagger_client.rest import ApiException


class TestForecastApi(unittest.TestCase):
    """ForecastApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.forecast_api.ForecastApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_forecast(self):
        """Test case for get_forecast

        Get balance forecast  # noqa: E501
        """
        pass

    def test_get_forecast_transactions(self):
        """Test case for get_forecast_transactions

        Retrieve balance forecast for the end of the current month.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
