# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.notification_api import NotificationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestNotificationApi(unittest.TestCase):
    """NotificationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.notification_api.NotificationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_notification(self):
        """Test case for delete_notification

        Delete notification  # noqa: E501
        """
        pass

    def test_get_notification(self):
        """Test case for get_notification

        Get notification   # noqa: E501
        """
        pass

    def test_get_notifications(self):
        """Test case for get_notifications

        List notifications  # noqa: E501
        """
        pass

    def test_post_balance_change_notification(self):
        """Test case for post_balance_change_notification

        Create a balance change notification  # noqa: E501
        """
        pass

    def test_post_budget_notification(self):
        """Test case for post_budget_notification

        Create a budget change notification  # noqa: E501
        """
        pass

    def test_post_daily_summary_notification(self):
        """Test case for post_daily_summary_notification

        Create a daily summary notification  # noqa: E501
        """
        pass

    def test_post_new_transaction_notification(self):
        """Test case for post_new_transaction_notification

        Create a new transaction notification  # noqa: E501
        """
        pass

    def test_put_notification(self):
        """Test case for put_notification

        Update notification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
