# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.registration_response import RegistrationResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestRegistrationResponse(unittest.TestCase):
    """RegistrationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRegistrationResponse(self):
        """Test RegistrationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.registration_response.RegistrationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
