# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tan_schemes_api import TANSchemesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTANSchemesApi(unittest.TestCase):
    """TANSchemesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tan_schemes_api.TANSchemesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_current_tan_media(self):
        """Test case for get_current_tan_media

        Get current TAN media.  # noqa: E501
        """
        pass

    def test_get_current_tan_scheme(self):
        """Test case for get_current_tan_scheme

        Get current TAN scheme.  # noqa: E501
        """
        pass

    def test_get_tan_schemes(self):
        """Test case for get_tan_schemes

        List TAN schemes for access  # noqa: E501
        """
        pass

    def test_put_current_tan_media(self):
        """Test case for put_current_tan_media

        Update current TAN media.  # noqa: E501
        """
        pass

    def test_put_current_tan_scheme(self):
        """Test case for put_current_tan_scheme

        Update current TAN scheme.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
