# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.access_api import AccessApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAccessApi(unittest.TestCase):
    """AccessApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.access_api.AccessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_access(self):
        """Test case for delete_access

        Delete access  # noqa: E501
        """
        pass

    def test_get_access(self):
        """Test case for get_access

        Get access  # noqa: E501
        """
        pass

    def test_get_accesses(self):
        """Test case for get_accesses

        List accesses  # noqa: E501
        """
        pass

    def test_get_asset(self):
        """Test case for get_asset

        Get transaction.  # noqa: E501
        """
        pass

    def test_list_assets(self):
        """Test case for list_assets

        Returns a list of assets for the related account represented by path  parameter accountId.  # noqa: E501
        """
        pass

    def test_post_access(self):
        """Test case for post_access

        Create a new access  # noqa: E501
        """
        pass

    def test_put_access(self):
        """Test case for put_access

        Update access  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
