# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.registration_api import RegistrationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRegistrationApi(unittest.TestCase):
    """RegistrationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.registration_api.RegistrationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_registration(self):
        """Test case for delete_registration

        Delete the user context for the current token.  # noqa: E501
        """
        pass

    def test_get_json_web_key(self):
        """Test case for get_json_web_key

        Request API jwk public key  # noqa: E501
        """
        pass

    def test_get_registration_public_key(self):
        """Test case for get_registration_public_key

        Request API public key  # noqa: E501
        """
        pass

    def test_register(self):
        """Test case for register

        User registration  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
