# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.notification import Notification  # noqa: F401,E501


class DailySummaryNotification(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_id': 'str',
        'time_of_day': 'str',
        'days_of_week': 'list[str]'
    }

    attribute_map = {
        'account_id': 'accountId',
        'time_of_day': 'timeOfDay',
        'days_of_week': 'daysOfWeek'
    }

    def __init__(self, account_id=None, time_of_day=None, days_of_week=None):  # noqa: E501
        """DailySummaryNotification - a model defined in Swagger"""  # noqa: E501

        self._account_id = None
        self._time_of_day = None
        self._days_of_week = None
        self.discriminator = None

        self.account_id = account_id
        self.time_of_day = time_of_day
        self.days_of_week = days_of_week

    @property
    def account_id(self):
        """Gets the account_id of this DailySummaryNotification.  # noqa: E501

        Identifier of the account to which this notification belongs  # noqa: E501

        :return: The account_id of this DailySummaryNotification.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this DailySummaryNotification.

        Identifier of the account to which this notification belongs  # noqa: E501

        :param account_id: The account_id of this DailySummaryNotification.  # noqa: E501
        :type: str
        """
        if account_id is None:
            raise ValueError("Invalid value for `account_id`, must not be `None`")  # noqa: E501

        self._account_id = account_id

    @property
    def time_of_day(self):
        """Gets the time_of_day of this DailySummaryNotification.  # noqa: E501

        Time of the day when this notification should be triggered. Must be in the desired timezone or normalized to UTC. (ISO-8601; e.g.,  \"13:45.30.123456789+02:00\")  # noqa: E501

        :return: The time_of_day of this DailySummaryNotification.  # noqa: E501
        :rtype: str
        """
        return self._time_of_day

    @time_of_day.setter
    def time_of_day(self, time_of_day):
        """Sets the time_of_day of this DailySummaryNotification.

        Time of the day when this notification should be triggered. Must be in the desired timezone or normalized to UTC. (ISO-8601; e.g.,  \"13:45.30.123456789+02:00\")  # noqa: E501

        :param time_of_day: The time_of_day of this DailySummaryNotification.  # noqa: E501
        :type: str
        """
        if time_of_day is None:
            raise ValueError("Invalid value for `time_of_day`, must not be `None`")  # noqa: E501

        self._time_of_day = time_of_day

    @property
    def days_of_week(self):
        """Gets the days_of_week of this DailySummaryNotification.  # noqa: E501

        The days of the week on which these notification should be triggered. All entries must be unique.  Can be `MONDAY`, `TUESDAY`, `WEDNESDAY`, `THURSDAY`, `FRIDAY`, `SATURDAY` or `SUNDAY`  # noqa: E501

        :return: The days_of_week of this DailySummaryNotification.  # noqa: E501
        :rtype: list[str]
        """
        return self._days_of_week

    @days_of_week.setter
    def days_of_week(self, days_of_week):
        """Sets the days_of_week of this DailySummaryNotification.

        The days of the week on which these notification should be triggered. All entries must be unique.  Can be `MONDAY`, `TUESDAY`, `WEDNESDAY`, `THURSDAY`, `FRIDAY`, `SATURDAY` or `SUNDAY`  # noqa: E501

        :param days_of_week: The days_of_week of this DailySummaryNotification.  # noqa: E501
        :type: list[str]
        """
        if days_of_week is None:
            raise ValueError("Invalid value for `days_of_week`, must not be `None`")  # noqa: E501
        allowed_values = ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY", "SUNDAY"]  # noqa: E501
        if not set(days_of_week).issubset(set(allowed_values)):
            raise ValueError(
                "Invalid values for `days_of_week` [{0}], must be a subset of [{1}]"  # noqa: E501
                .format(", ".join(map(str, set(days_of_week) - set(allowed_values))),  # noqa: E501
                        ", ".join(map(str, allowed_values)))
            )

        self._days_of_week = days_of_week

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DailySummaryNotification):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
