# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class RegistrationResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'installation': 'str'
    }

    attribute_map = {
        'installation': 'installation'
    }

    def __init__(self, installation=None):  # noqa: E501
        """RegistrationResponse - a model defined in Swagger"""  # noqa: E501

        self._installation = None
        self.discriminator = None

        if installation is not None:
            self.installation = installation

    @property
    def installation(self):
        """Gets the installation of this RegistrationResponse.  # noqa: E501

        api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationResponseDto.properties.installation.description  # noqa: E501

        :return: The installation of this RegistrationResponse.  # noqa: E501
        :rtype: str
        """
        return self._installation

    @installation.setter
    def installation(self, installation):
        """Sets the installation of this RegistrationResponse.

        api.dto.model.com-starfinanz-ahoi-dto-v2-RegistrationResponseDto.properties.installation.description  # noqa: E501

        :param installation: The installation of this RegistrationResponse.  # noqa: E501
        :type: str
        """

        self._installation = installation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RegistrationResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
