# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class ResponseObjectMap(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'username': 'str',
        'customernumber': 'str',
        'pin': 'str',
        'tan': 'str'
    }

    attribute_map = {
        'username': 'USERNAME',
        'customernumber': 'CUSTOMERNUMBER',
        'pin': 'PIN',
        'tan': 'TAN'
    }

    def __init__(self, username=None, customernumber=None, pin=None, tan=None):  # noqa: E501
        """ResponseObjectMap - a model defined in Swagger"""  # noqa: E501

        self._username = None
        self._customernumber = None
        self._pin = None
        self._tan = None
        self.discriminator = None

        if username is not None:
            self.username = username
        if customernumber is not None:
            self.customernumber = customernumber
        if pin is not None:
            self.pin = pin
        if tan is not None:
            self.tan = tan

    @property
    def username(self):
        """Gets the username of this ResponseObjectMap.  # noqa: E501

        The username for the authorization.  # noqa: E501

        :return: The username of this ResponseObjectMap.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this ResponseObjectMap.

        The username for the authorization.  # noqa: E501

        :param username: The username of this ResponseObjectMap.  # noqa: E501
        :type: str
        """

        self._username = username

    @property
    def customernumber(self):
        """Gets the customernumber of this ResponseObjectMap.  # noqa: E501

        The username for the authorization.  # noqa: E501

        :return: The customernumber of this ResponseObjectMap.  # noqa: E501
        :rtype: str
        """
        return self._customernumber

    @customernumber.setter
    def customernumber(self, customernumber):
        """Sets the customernumber of this ResponseObjectMap.

        The username for the authorization.  # noqa: E501

        :param customernumber: The customernumber of this ResponseObjectMap.  # noqa: E501
        :type: str
        """

        self._customernumber = customernumber

    @property
    def pin(self):
        """Gets the pin of this ResponseObjectMap.  # noqa: E501

        The PIN for the authorization  # noqa: E501

        :return: The pin of this ResponseObjectMap.  # noqa: E501
        :rtype: str
        """
        return self._pin

    @pin.setter
    def pin(self, pin):
        """Sets the pin of this ResponseObjectMap.

        The PIN for the authorization  # noqa: E501

        :param pin: The pin of this ResponseObjectMap.  # noqa: E501
        :type: str
        """

        self._pin = pin

    @property
    def tan(self):
        """Gets the tan of this ResponseObjectMap.  # noqa: E501

        The TAN for the authorization.  # noqa: E501

        :return: The tan of this ResponseObjectMap.  # noqa: E501
        :rtype: str
        """
        return self._tan

    @tan.setter
    def tan(self, tan):
        """Sets the tan of this ResponseObjectMap.

        The TAN for the authorization.  # noqa: E501

        :param tan: The tan of this ResponseObjectMap.  # noqa: E501
        :type: str
        """

        self._tan = tan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ResponseObjectMap):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
