# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.additional_information import AdditionalInformation  # noqa: F401,E501


class Transaction(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'transaction_pattern_id': 'str',
        'additional_information': 'list[AdditionalInformation]',
        'type': 'str'
    }

    attribute_map = {
        'id': 'id',
        'transaction_pattern_id': 'transactionPatternId',
        'additional_information': 'additionalInformation',
        'type': 'type'
    }

    discriminator_value_class_map = {
        'GiroTransaction': 'GiroTransaction'
    }

    def __init__(self, id=None, transaction_pattern_id=None, additional_information=None, type=None):  # noqa: E501
        """Transaction - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._transaction_pattern_id = None
        self._additional_information = None
        self._type = None
        self.discriminator = 'type'

        self.id = id
        if transaction_pattern_id is not None:
            self.transaction_pattern_id = transaction_pattern_id
        if additional_information is not None:
            self.additional_information = additional_information
        self.type = type

    @property
    def id(self):
        """Gets the id of this Transaction.  # noqa: E501

        Internal ID of this transaction (generated value)  # noqa: E501

        :return: The id of this Transaction.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Transaction.

        Internal ID of this transaction (generated value)  # noqa: E501

        :param id: The id of this Transaction.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def transaction_pattern_id(self):
        """Gets the transaction_pattern_id of this Transaction.  # noqa: E501

        Identifier of the transactionPattern to which this transaction belongs  # noqa: E501

        :return: The transaction_pattern_id of this Transaction.  # noqa: E501
        :rtype: str
        """
        return self._transaction_pattern_id

    @transaction_pattern_id.setter
    def transaction_pattern_id(self, transaction_pattern_id):
        """Sets the transaction_pattern_id of this Transaction.

        Identifier of the transactionPattern to which this transaction belongs  # noqa: E501

        :param transaction_pattern_id: The transaction_pattern_id of this Transaction.  # noqa: E501
        :type: str
        """

        self._transaction_pattern_id = transaction_pattern_id

    @property
    def additional_information(self):
        """Gets the additional_information of this Transaction.  # noqa: E501


        :return: The additional_information of this Transaction.  # noqa: E501
        :rtype: list[AdditionalInformation]
        """
        return self._additional_information

    @additional_information.setter
    def additional_information(self, additional_information):
        """Sets the additional_information of this Transaction.


        :param additional_information: The additional_information of this Transaction.  # noqa: E501
        :type: list[AdditionalInformation]
        """

        self._additional_information = additional_information

    @property
    def type(self):
        """Gets the type of this Transaction.  # noqa: E501

        Discriminator for subtypes. At the moment only `GiroTransaction` is supported.  # noqa: E501

        :return: The type of this Transaction.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Transaction.

        Discriminator for subtypes. At the moment only `GiroTransaction` is supported.  # noqa: E501

        :param type: The type of this Transaction.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def get_real_child_model(self, data):
        """Returns the real base class specified by the discriminator"""
        discriminator_value = data[self.discriminator].lower()
        return self.discriminator_value_class_map.get(discriminator_value)

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Transaction):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
