# coding: utf-8

"""
    

    [AHOI cookbook](/ahoi/docs/cookbook/index.html)  [Data Privacy](/sandboxmanager/#/privacy)  [Terms of Service](/sandboxmanager/#/terms)  [Imprint](https://sparkassen-hub.com/impressum/)  &copy; 2016&dash;2017 Starfinanz - Ein Unternehmen der Finanz Informatik  # noqa: E501

    OpenAPI spec version: 2.1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class TransferTask(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'state': 'str',
        'transfer_task_id': 'str'
    }

    attribute_map = {
        'state': 'state',
        'transfer_task_id': 'transferTaskId'
    }

    def __init__(self, state=None, transfer_task_id=None):  # noqa: E501
        """TransferTask - a model defined in Swagger"""  # noqa: E501

        self._state = None
        self._transfer_task_id = None
        self.discriminator = None

        if state is not None:
            self.state = state
        if transfer_task_id is not None:
            self.transfer_task_id = transfer_task_id

    @property
    def state(self):
        """Gets the state of this TransferTask.  # noqa: E501

        STATE - The State of the corresponding Transfer.  # noqa: E501

        :return: The state of this TransferTask.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this TransferTask.

        STATE - The State of the corresponding Transfer.  # noqa: E501

        :param state: The state of this TransferTask.  # noqa: E501
        :type: str
        """

        self._state = state

    @property
    def transfer_task_id(self):
        """Gets the transfer_task_id of this TransferTask.  # noqa: E501

        transferTaskId - The ID of the Task.  # noqa: E501

        :return: The transfer_task_id of this TransferTask.  # noqa: E501
        :rtype: str
        """
        return self._transfer_task_id

    @transfer_task_id.setter
    def transfer_task_id(self, transfer_task_id):
        """Sets the transfer_task_id of this TransferTask.

        transferTaskId - The ID of the Task.  # noqa: E501

        :param transfer_task_id: The transfer_task_id of this TransferTask.  # noqa: E501
        :type: str
        """

        self._transfer_task_id = transfer_task_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TransferTask):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
